apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "control-plane.fullname" . }}-netpol
  labels:
    app.kubernetes.io/name: {{ include "control-plane.name" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "control-plane.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "agent"
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "gateway"
  egress:
    # Allow DNS resolution queries to kube-dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
